---
layout: translation
id: eaf96030f854cd5a93de5af2c5f2bc0b1e18efda
title: Cicero&#58; In Verrem II Übersetzung (Buch I)
title_nav: In Verrem II (Buch I)
heading: Cicero&#58; In Verrem II
chapters:
  - number: 32
    latin: >-
      Nunc mihi temporis eius quod mihi ad dicendum datur, quoniam in animo est causam omnem exponere, habenda ratio est diligenter. Itaque primum illum actum istius vitae turpissimum et flagitiosissimum praetermittam. Nihil a me de pueritiae suae flagitiis peccatisque audiet, nihil ex illa impura adulescentia sua; quae qualis fuerit aut meministis, aut ex eo quem sui simillimum produxit recognoscere potestis. Omnia praeteribo quae mihi turpia dictu videbuntur, neque solum quid istum audire, verum etiam quid me deceat dicere considerabo. Vos, quaeso, date hoc et concedite pudori meo ut aliquam partem de istius impudentia reticere possim. 
    german: >-
      Nun muss ich die Zeit, die mir zum Sprechen gegeben wird, sorgfältig einteilen, da ich ja im Sinn habe, den ganzen Rechtsfall darzulegen. Deshalb werde ich jenen ersten und sehr schädlichen sowie sehr schimpflichen Abschnitt des Lebens von diesem da übergehen. Nichts wird er von mir über die Schandtaten aus seiner Kindheit hören, nichts aus jener unanständigen Jugend. Wie diese war, könnt ihr erkennen; entweder ihr erinnert euch, oder ihr könnt es an dem erkennen, den er als sein Ebenbild mitgebracht hat. Ich werde alles übergehen, was mir schändlich zu sagen scheinen wird, und ich werde nicht nur überlegen, was sich für diesen da zu hören ziemt, sondern auch, was sich für mich zu sagen gehört. Bitte gewährt mir dies und erlaubt meinem Anstand, dass ich einen Teil über die Schamlosigkeit von diesem da verschweigen kann.
  - latin: >-
      Omne illud tempus quod fuit antequam iste ad magistratus remque publicam accessit, habeat per me solutum ac liberum. Sileatur de nocturnis eius bacchationibus ac vigiliis; lenonum, aleatorum, perductorum nulla mentio fiat; damna, dedecora, quae res patris eius, aetas ipsius pertulit, praetereantur; lucretur indicia veteris infamiae; patiatur eius vita reliqua me hanc tantam iacturam criminum facere.
    german: >-
      Die ganze Zeit, die war, bevor sich dieser da in den Ämtern und der Politik betätigte, soll von mir unberücksichtigt und unberührt bleiben. Seine nächtlichen Orgien und durchzechten Nächte sollen verschwiegen werden; die Kuppler, Glücksspieler und Zuhälter sollen keine Erwähnung finden. Die Verluste und Blamagen, die das Vermögen seines Vaters und seine eigene Jugend erlitten haben, sollen vernachlässigt werden. Er soll herumkommen um die Hinweise auf seine alten Schandtaten; sein übriges Leben soll ertragen, dass ich so viele Verbrechen auslasse.
  - number: 46
    latin: >-
      Delum venit. Ibi ex fano Apollinis religiosissimo noctu clam sustulit signa pulcherrima atque antiquissima, eaque in onerariam navem. suam conicienda curavit. Postridie cum fanum spoliatum viderent ii qui Delum incolebant, graviter ferebant; est enim tanta apud eos eius fani religio atque antiquitas ut in eo loco ipsum Apollinem natum esse arbitrentur. Verbum tamen facere non audebant, ne forte ea res ad Dolabellam ipsum pertineret. Tum subito tempestates coortae sunt maximae, iudices, ut non modo proficisci cum cuperet Dolabella non posset sed vix in oppido consisteret: ita magni fluctus eiciebantur. Hic navis illa praedonis istius, onusta signis religiosis, expulsa atque eiecta fluctu frangitur; in litore signa illa Apollinis reperiuntur; iussu Dolabellae reponuntur. Tempestas sedatur, Dolabella Delo proficiscitur. 
    german: >-
      Er kam nach Delos. Dort hat er aus einem sehr ehrwürdigen Tempel Apolls heimlich in der Nacht sehr schöne und uralte Standbilder beseitigt und ließ diese auf sein Lastschiff bringen. Als am Tag darauf die Bewohner von Delos den ausgeplünderten Tempel sahen, ertrugen sie es schwer. Denn die religöse Verehrung und das hohe Alter dieses Tempels ist bei ihnen so groß, dass sie glauben, dass Apoll selbst an diesem Ort geboren sei. Dennoch wagten sie kein Wort zu äußern, aus Besorgnis, die Sache möchte vielleicht Dolabella selbst berühren. Dann erhoben sich sofort sehr große Unwetter, Richter, dass nicht nur nicht Dolabella, obwohl er wollte, aufbrechen konnte, sondern kaum in der Stadt bleiben konnte: Solch heftige Wellen wurden <span class="annotation">[von der See]</span> ausgeworfen. Da wurde jenes Schiff dieses Räubers, das mit den heiligen Standbildern beladen war, hinausgeworfen und vertrieben und von der Flut zerbrochen; an der Küste wurden jene Statuen des Apolls wiedergefunden; auf Dolabellas Befehl wurden sie zurückgestellt. Der Sturm legte sich, Dolabella reiste aus Delos ab.
source_latin: http://www.thelatinlibrary.com/cicero/verres.2.1.shtml
counter: https://www.webfreecounter.com/hit.php?id=zmqppo&nd=9&style=44
---