---
layout: translation
title: Cäsar&#58; De Bello Gallico Übersetzung (Buch VI)
title_nav: De Bello Gallico (Buch VI)
heading: Cäsar&#58; De Bello Gallico
chapters: 
  - number: 13
    latin: >-
      In omni Gallia eorum hominum, qui aliquo sunt numero atque honore, genera sunt duo. Nam plebes paene servorum habetur loco, quae nihil audet per se, nullo adhibetur consilio. Plerique, cum aut aere alieno aut magnitudine tributorum aut iniuria potentiorum premuntur, sese in servitutem dicant nobilibus: in hos eadem omnia sunt iura, quae dominis in servos. Sed de his duobus generibus alterum est druidum, alterum equitum. [...]
    german: >-
      In ganz Gallien gibt es 2 Arten von den Menschen, die irgendwelche Bedeutung Geltung haben. Denn das Volk wird beinahe wie Sklaven betrachtet, da es von sich aus nichts wagt und zu keinem Rat hinzugezogen wird. Die meisten begeben sich in Sklaverei, wenn sie durch Schulden oder durch die Größe der Aufgaben oder Unrecht durch die Mächtigeren bedrängt werden. Diese <span class="annotation">(die Adeligen)</span> haben ihnen gegenüber dieselben Rechte wie Herren gegenüber den Sklaven. Von diesen 2 Arten ist die eine die der Druiden, die andere die der Reiter. [...]
  - number: 16
    latin: >-
      Natio est omnis Gallorum admodum dedita religionibus, atque ob eam causam, qui sunt adfecti gravioribus morbis quique in proeliis periculisque versantur, aut pro victimis homines immolant aut se immolaturos vovent administrisque ad ea sacrificia druidibus utuntur, quod, pro vita hominis nisi hominis vita reddatur, non posse deorum immortalium numen placari arbitrantur, publiceque eiusdem generis habent instituta sacrificia. Alii immani magnitudine simulacra habent, quorum contexta viminibus membra vivis hominibus complent; quibus succensis circumventi flamma exanimantur homines.  Supplicia eorum qui in furto aut in latrocinio aut aliqua noxia sint comprehensi gratiora dis immortalibus esse arbitrantur; sed, cum eius generis copia defecit, etiam ad innocentium supplicia descendunt. 
    german: >-
      Das ganze Volk der Gallier ist völlig der Götterverehrung hingegeben, deswegen opfern die, die von schwereren Krankheiten befallen sind und diese, die sich in Schlachten und Gefahren aufhalten, entweder an Stelle der Opfertiere Menschen, oder sie schwören, dass sie sie opfern werden; und sie verwenden Druiden als Helfer für diese Opfer, weil sie glauben, dass der Wille der unsterblichen Götter nicht besänftigt werden kann, wenn nicht für das Leben eines Menschen das eines anderen zrückgegeben wird, und sie haben öffentlich eingerichtetet Opferhandlungen dieser Art. Einige Stämme haben riesig große Götzenbilder aus Weidengeflecht, deren Glieder sie mit lebenden Menschen anfüllen; diese werden dann von unten nach oben angezündet und so die Unglücklichen dem Feuertod geweiht. Sie glauben, dass die Hinrichtung derer, die in einem Diebstahl, Raub oder einem anderen Vergehen ergriffen wurden, den unsterblichen Göttern willkommener seien; wenn aber die Menge dieser Art fehlt, steigen sie auch herab zu Hinrichtungen Unschuldiger.
  - number: 21
    latin: >-
      Germani multum ab hac consuetudine differunt. Nam neque druides habent, qui rebus divinis praesint, neque sacrificiis student. Deorum numero eos solos ducunt, quos cernunt et quorum aperte opibus iuvantur, Solem et Vulcanum et Lunam, reliquos ne fama quidem acceperunt. Vita omnis in venationibus atque in studiis rei militaris consistit: ab parvulis labori ac duritiae student. Qui diutissime impuberes permanserunt, maximam inter suos ferunt laudem: hoc ali staturam, ali vires nervosque confirmari putant. Intra annum vero vicesimum feminae notitiam habuisse in turpissimis habent rebus; cuius rei nulla est occultatio, quod et promiscue in fluminibus perluuntur et pellibus aut parvis renonum tegimentis utuntur magna corporis parte nuda.
    german: >-
      Die Germanen unterscheiden sich viel von der Gewohnheit der Gallier. Denn sie haben weder Druiden, die den göttlichen Angelegenheiten vorstehen, noch bemühen sie sich um Opfer. Zu den Göttern rechnen sie nur die, die sie sehen und durch deren Macht sie offenkundig unterstützt werden; die Sonne, den Vulkan und den Mond. Von den übrigen Göttern haben sie nicht einmal durch Hörensagen erfahren. Ihr ganzes Leben besteht aus Jagden und aus den Bemühungen um das Kriegswesen; von klein auf bemühen sie sich um Arbeit und Abhärtung. Jenen, die am längsten ohne sexuellen Kontakt bleiben, bringen sie das größte Lob entgegen: Sie glauben, dass dadurch der Körperbau und die Kräfte gefördert und die Muskeln gestärkt werden. Dagegen rechnen sie es aber zu den schändlichsten Dingen, vor dem 20. Lebensjahr sexuellen Kontakt mit einer Frau gehabt zu haben. Trotzdem gibt es in dieser Hinsicht keine Heimlichtuereien, weil sie sich sowohl gemeinsam in Flüssen waschen als auch Felle oder kleine Felzbedeckungen nutzen, wobei ein großer Teil des Körpers nackt ist.
  - latin: >-
      Agriculturae non student, maiorque pars eorum victus in lacte, caseo, carne consistit. Neque quisquam agri modum certum aut fines habet proprios; sed magistratus ac principes in annos singulos gentibus cognationibusque hominum, qui una coierunt, quantum et quo loco visum est agri attribuunt atque anno post alio transire cogunt. Eius rei multas adferunt causas: ne adsidua consuetudine capti studium belli gerendi agricultura commutent; ne latos fines parare studeant, potentioresque humiliores possessionibus expellant; ne accuratius ad frigora atque aestus vitandos aedificent; ne qua oriatur pecuniae cupiditas, qua ex re factiones dissensionesque nascuntur; ut animi aequitate plebem contineant, cum suas quisque opes cum potentissimis aequari videat. 
    german: >-
      Sie bemühen sich nicht um Ackerbau, der größere Teil ihrer Nahrung besteht aus Milch, Käse und Fleisch. Kaum jemand besitzt bei ihnen ein bestimmtes Maß an Feldern oder eigene Gebiete, sondern Beamte und führende Männer teilen jährlich den Familien und Verwandten Felder zu, im nächsten Jahr zwingen sie sie, woanders hinzuziehen. Dafür führen sie viele Gründe an: damit sie nicht das Streben nach Kriegsführung gegen Ackerbau eintauschen; damit sie sich nicht bemühen, weite Gebiete zu erwerben und die Mächtigeren nicht die Niedrigeren aus ihren Besitztümern vertreiben; damit sie nicht allzu sorgfältig bauen zum Meiden von Kälte und Hitze; damit keine Geldgier entsteht, woraus Verfeindungen und Aufstände entstehen; und damit das Volk durch Gelassenheit zusammenhält, weil jeder sieht, dass seine Reichtümer mit denen der Mächtigsten gleichgestellt werden.
  - latin: >-
      Civitatibus maxima laus est quam latissime circum se vastatis finibus solitudines habere. Hoc proprium virtutis existimant, expulsos agris finitimos cedere, neque quemquam prope audere consistere; simul hoc se fore tutiores arbitrantur repentinae incursionis timore sublato. Cum bellum civitas aut illa tum defendit aut infert, magistratus, qui ei bello praesint, ut vitae necisque habeant potestatem, deliguntur. In pace nullus est communis magistratus, sed principes regionum atque pagorum inter suos ius dicunt controversiasque minuunt.  Latrocinia nullam habent infamiam, quae extra fines cuiusque civitatis fiunt, atque ea iuventutis exercendae ac desidiae minuendae causa fieri praedicant.  Atque ubi quis ex principibus in concilio dixit se ducem fore, qui sequi velint, profiteantur, consurgunt ei qui et causam et hominem probant suumque auxilium pollicentur atque ab multitudine collaudantur: qui ex his secuti non sunt, in desertorum ac proditorum numero ducuntur, omniumque his rerum postea fides derogatur. Hospitem violare fas non putant; qui quacumque de causa ad eos venerunt, ab iniuria prohibent, sanctos habent, hisque omnium domus patent victusque communicatur. 
    german: >-
      Für die Stämme ist es das größte Lob, nach Verwüstung des Gebiets möglichst weit um sich herum Einsamkeit zu haben. Sie halten es für ein Kennzeichen von Tapferkeit, dass die aus ihren Feldern vertriebenen Nachbarn weichen und keiner es wagt, sich in ihrer Nähe niederzulassen. Gleichzeitig glauben sie, dass sie dadurch sicherer sein würden, nachdem die Angst vor einem plötzlichen Angriff aufgehoben worden ist. Wenn ein Stamm einen Angriffskrieg entweder verteidigt oder selbst beginnt, werden Beamte gewählt, die diesem Krieg vorstehen und Macht über Leben und Tod haben. Im Frieden gibt es keine Beamte, sondern führende Männer aus Gebieten und Dörfern sprechen untereinenader Recht und verringern Streitigkeiten. Raubzüge gelten als nicht schändlich, wenn sie außerhalb des eigenen Stammesgebiets geschehen; sie rühmen sie sogar als Mittel gegen den Müßiggang und zur Ertüchtigung der Jugend. Sobald irgendeiner der führenden Männer in der Versammlung sagt, dass er Anführer sein wolle und diejenigen, die ihm folgen wollen, sich dazu bekennen sollen, so erheben sich alle, die sowohl die Sache als auch den Mann gut finden und versprechen ihm unter lautem Beifall der Menge ihre Unterstützung. Jene, die ihm aber später dennoch nicht folgen, werden zu den Fahnenflüchtigen und Verrätern gerechnet, und das Vertrauen in allen Dingen wird ihnen später entzogen. Sie halten es für ein No-Go <span class="annotation">(wörtlich: "nicht für ein göttliches Recht")</span>, einen Gast zu verletzen; wenn einer aus welchem Grund auch immer zu ihnen gekommen ist, so schätzen sie ihn als unverletzlich gegen jede Beleidigung, die Häuser aller stehen ihm offen und die Nahrung wird zu einer gemeinschaftlichen gemacht.
  - number: 24
    latin: >-
      Ac fuit antea tempus, cum Germanos Galli virtute superarent, ultro bella inferrent, propter hominum multitudinem agrique inopiam trans Rhenum colonias mitterent. Itaque ea quae fertilissima Germaniae sunt loca circum Hercyniam silvam, quam Eratostheni et quibusdam Graecis fama notam esse video, quam illi Orcyniam appellant, Volcae Tectosages occupaverunt atque ibi consederunt; quae gens ad hoc tempus his sedibus sese continet summamque habet iustitiae et bellicae laudis opinionem. Nunc quod in eadem inopia, egestate, patientia qua Germani permanent, eodem victu et cultu corporis utuntur; Gallis autem provinciarum propinquitas et transmarinarum rerum notitia multa ad copiam atque usus largitur, paulatim adsuefacti superari multisque victi proeliis ne se quidem ipsi cum illis virtute comparant.
    german: >-
      Früher gab es eine Zeit, als die Gallier die Germanen an Tapferkeit übertrafen, aus freien Stücken Kriege <span class="annotation">[gegen sie]</span> begannen und wegen der großen Zahl an Menschen <span class="annotation">(überbevölkerung)</span> und des Mangels an Ackerland Siedler über den Rhein schickten. Und so besetzten die Tektosagen, ein Stamm der Volker, die Orte, die die fruchtbarsten Germaniens um den Herkynischen Wald herum sind, der, wie ich sehe, schon Eratosthenes und gewissen <span class="annotation">[anderen]</span> Griechen unter dem Namen Orkynischer Wald durch Hörensagen bekannt war, und ließen sich dort nieder. Dieser Stamm erhält sich bis zu dieser Zeit an diesen Sitzen und hat den höchsten Ruf von Gerechtigkeit und Kriegsruhm. Die Germanen benutzen jetzt <span class="annotation">[immer noch]</span> dieselbe Lebensweise und Körperpflege, da sie ja auf demselben Mangel und derselben Dürftigkeit und Genügsamkeit verharren. Den Galliern aber verschafft die Nähe römischer Provinzen und die Bekanntschaft mit den über das Meer kommenden Waren mehr zum eigenen Wohlstand und Luxus. Allmählich sind sie daran gewöhnt besiegt zu werden und vergleichen sich nach vielen Niederlagen nicht einmal mehr selbst an Tapferkeit mit den Germanen.
  - number: 25
    latin: >-
      Huius Hercyniae silvae, quae supra demonstrata est, latitudo novem dierum iter expedito patet: non enim aliter finiri potest, neque mensuras itinerum noverunt. Oritur ab Helvetiorum et Nemetum et Rauracorum finibus rectaque fluminis Danubi regione pertinet ad fines Dacorum et Anartium; hinc se flectit sinistrorsus diversis ab flumine regionibus multarumque gentium fines propter magnitudinem adtingit; neque quisquam est huius Germaniae, qui se aut adisse ad initium eius silvae dicat, cum dierum iter LX processerit, aut, quo ex loco oriatur, acceperit: multaque in ea genera ferarum nasci constat, quae reliquis in locis visa non sint; ex quibus quae maxime differant ab ceteris et memoriae prodenda videantur haec sunt. 
    german: >-
      Die Weite des Herkynischen Waldes, auf den oben hingewiesen wurde, erstreckt sich auf einen Fußmarsch von 9 Tagen für einen unbepackten Fußgänger: Anders kann er nämlich nicht begrenzt werden, denn die Germanen kennen keine Maße für Märsche. Er beginnt im Gebiet der Helvetier, Nemeter und Rauraker und erstreckt sich in gerader Richtung mit dem Fluss Donau zu den Dakern und Anarten. Von hier biegt er sich nach links zu Gegenden, die vom Fluss abgelegen sind und berührt aufgrund seiner Größe viele Gebiete, die vom Fluss abgelegen sind. Niemand in diesen Gegenden Germaniens, selbst wenn er 60 Tage auf der Reise war, kann behaupten, dass er den Anfangspunkt des Waldes gesehen oder etwas Bestimmtes darüber erfahren habe. Und es steht fest, dass viele Arten von Tieren in diesem Wald geboren werden, die an den übrigen Orten noch nie gesehen wurden. Von diesen sind die, die sich am meisten von den anderen unterscheiden und scheinen, dass sie überliefert werden müssten, die Folgenden:
  - number: 26
    latin: >-
      Est bos cervi figura, cuius a media fronte inter aures unum cornu exsistit excelsius magisque directum his, quae nobis nota sunt, cornibus: ab eius summo sicut palmae ramique late diffunduntur. Eadem est feminae marisque natura, eadem forma magnitudoque cornuum. 
    german: >-
      Es gibt ein Rind mit der Gestalt eines Hirschen<sup>1</sup>. Mitten von dessen Stirn tritt zwischen den Ohren ein einziges Horn hervor, das höher und gerader ist als die uns bekannten Hirschgeweihe. Von dessen Spitze breitet sich das Horn aus, wie sich Hände oder Zweige weit ausbreiten.  Das Wesen des Weibchens und des das des Männchens ist dasselbe, ebenso die Gestalt und Größe des Geweihes.
    footnotes:
      - number: 1
        content: Gemeint ist hier das Rentier
  - number: 27
    latin: >-
      Sunt item, quae appellantur alces. Harum est consimilis capris figura et varietas pellium, sed magnitudine paulo antecedunt mutilaeque sunt cornibus et crura sine nodis articulisque habent neque quietis causa procumbunt neque, si quo adflictae casu conciderunt, erigere sese aut sublevare possunt. His sunt arbores pro cubilibus: ad eas se applicant atque ita paulum modo reclinatae quietem capiunt. Quarum ex vestigiis cum est animadversum a venatoribus, quo se recipere consuerint, omnes eo loco aut ab radicibus subruunt aut accidunt arbores, tantum ut summa species earum stantium relinquatur. Huc cum se consuetudine reclinaverunt, infirmas arbores pondere adfligunt atque una ipsae concidunt. 
    german: >-
      Es gibt ebenso Tiere, die Elche genannt werden. Deren Gestalt und Verschiedenartigkeit der Felle ist den Ziegen ähnlich, aber an Größe übertreffen sie sie ein wenig. An den Hörnern sind sie verstümmelt und sie haben Unterschenkel ohne Knöchel und Gelenke. Weder legen sie sich zur Ruhe hin noch können sie, wenn sie durch irgendeinen Zufall umgeworfen wurden, sich wieder aufrichten oder aufstehen. Ihnen dienen Bäume als Schlafstätten. Sie lehnen sich an ihnen an und fassen so, nur ein wenig rückwärts an diesen angelehnt, Ruhe. Wenn Jäger durch Fußspuren bemerkt haben, wohin sie sich gewöhnlich zurückziehen, untergraben sie dort alle Bäume oder kerben sie sie gerade so sehr ein, dass im Ganzen noch der Eindruck stehender Bäume bleibt. Wenn die Elche sich ihrer Gewohnheit nach hier angelehnt haben, bringen sie die schwachen Bäume durch ihr Gewicht zu Fall und werden dann selbst getötet.
  - number: 28
    latin: >-
      Tertium est genus eorum, qui uri appellantur. Hi sunt magnitudine paulo infra elephantos, specie et colore et figura tauri. Magna vis eorum est et magna velocitas, neque homini neque ferae quam conspexerunt parcunt. Hos studiose foveis captos interficiunt. Hoc se labore durant adulescentes atque hoc genere venationis exercent, et qui plurimos ex his interfecerunt, relatis in publicum cornibus, quae sint testimonio, magnam ferunt laudem. Sed adsuescere ad homines et mansuefieri ne parvuli quidem excepti possunt. 5 Amplitudo cornuum et figura et species multum a nostrorum boum cornibus differt. Haec studiose conquisita ab labris argento circumcludunt atque in amplissimis epulis pro poculis utuntur.
    german: >-
      Die dritte Art von diesen <span class="annotation">[speziellen Tieren]</span> wird Auerochse genannt. Diese sind an Größe etwas kleiner als Elefanten, ihrem Aussehen, ihrer Farbe und Gestalt nach sind sie Stiere. Sie haben große Kraft und Schnelligkeit; sie schonen weder Mensch noch Tier, das sie erblickt haben. Nachdem sie eifrig in Gruben gefangen wurden, töten die Germanen sie. Durch diese Arbeit härten sich die jungen Männer ab und trainieren durch diese Art der Jagd. Diejenigen, die am meisten von diesen getötet haben, bekommen großes Lob, nachdem die als Beweis dienenden Hörner in der Öffentlichkeit verkündet wurden. Nicht einmal die sehr kleinen Auerochsen, die aus der Wildnis eingefangen wurden, können sich an die Menschen gewöhnen und zahm werden. Die Weite, Gestalt und das Aussehen ihrer Hörner unterscheiden sich sehr von den Hörnern unserer Ochsen. Die Germanen umschließen diese Hörner, die eifrig zusammengesucht worden sind, am Rand mit Silber und verwenden sie bei sehr prächtigen Festmählern an Stelle von Bechern.
source_latin: http://www.thelatinlibrary.com/caesar/gall6.shtml
counter: https://www.webfreecounter.com/hit.php?id=zrrvkxkx&nd=9&style=44
---