---
layout: translation
id: 9742c58619221918d01b9816999788f0ad8b8a5d
title: Plinius&#58; Epistulae Übersetzung (Buch X)
title_nav: Epistulae (Buch X)
heading: Plinius&#58; Epistulae
chapters:
  - number: 96
    latin: >-
      C. Plinius Traiano Imperatori. Sollemne est mihi, domine, omnia de quibus dubito ad te referre. Quis enim potest melius vel cunctationem meam regere vel ignorantiam instruere? Cognitionibus de Christianis interfui numquam: ideo nescio quid et quatenus aut puniri soleat aut quaeri. Nec mediocriter haesitavi, sitne aliquod discrimen aetatum, an quamlibet teneri nihil a robustioribus differant; detur paenitentiae venia, an ei, qui omnino Christianus fuit, desisse non prosit; nomen ipsum, si flagitiis careat, an flagitia cohaerentia nomini puniantur. Interim, iis qui ad me tamquam Christiani deferebantur, hunc sum secutus modum. Interrogavi ipsos an essent Christiani. Confitentes iterum ac tertio interrogavi supplicium minatus; perseverantes duci iussi. Neque enim dubitabam, qualecumque esset quod faterentur, pertinaciam certe et inflexibilem obstinationem debere puniri. Fuerunt alii similis amentiae, quos, quia cives Romani erant, adnotavi in urbem remittendos. Mox ipso tractatu, ut fieri solet, diffundente se crimine plures species inciderunt. Propositus est libellus sine auctore multorum nomina continens. [...]
    german: >-
      C. Plinius an seinen Kaiser Trajan. Ich habe die Gewohnheit, dir alles zu melden, worüber ich unsicher bin. Wer nämlich könnte besser entweder mein Zweifeln verstehen oder meine Unkenntnis beseitigen? Niemals habe ich an gerichtlichen Untersuchungen gegen die Christen teilgenommen, deshalb weiß ich nicht, was und in welchem Ausmaß gewöhnlich entweder bestraft oder verfolgt wird. Und ich habe nicht mittelmäßig <span class="annotation">(wenig)</span> gezweifelt, ob es <span class="annotation">[bei dieser Bestrafung]</span> irgendeinen Unterschied im Alter gibt oder ob sich die noch so Jungen nicht von den Älteren unterscheiden. Soll der Reue Nachsicht geschenkt werden, oder nutzt es dem, der Christ gewesen ist, gar nicht, aufgehört zu haben? Soll die Bezeichnung selbst, wenn er frei von Fehlern ist, oder nur Verbrechen, die im Zusammenhang mit dieser stehen, bestraft werden? Einst habe ich diese Art und Weise bei denen angewandt, die bei mir als Christen gemeldet worden sind: Ich habe sie selbst gefragt, ob sie Christen seien. Die Bekennenden habe ich wiederum gefragt, und beim drittem Mal unter Androhung der Todesstrafe. Ich befahl, dass die Verharrenden abgeführt werden. Ich zweifelte auch nicht daran, dass, was auch immer sie zugeben, beständiger Starrsinn und unbeugsamer Trotz bestraft werden müssen. Es gab bereits andere mit ähnlichem Wahnsinn, die ich, weil sie römische Bürger waren, vorgemerkt habe, um sie in die Stadt zurückzuschicken. Bald darauf ergaben sich bei der Verhandlung selbst, wie es oft geschieht, mehrere Vorfälle, während sich das Verbrechen ereignete. Mir wurde ein Büchlein ohne Verfasser vorgelegt, das die Namen vieler <span class="annotation">[dieser Christen]</span> enthielt. [...]
source_latin: https://www.thelatinlibrary.com/pliny.ep10.html
counter: https://www.webfreecounter.com/hit.php?id=grxqnfc&nd=9&style=44
---