---
layout: translation
id: a050c4ded6f86c519cd71671d5c60cd514d669b5
title: Sueton&#58; Divus Julius Übersetzung
title_nav: Divus Julius
heading: Sueton&#58; Divus Julius
chapters:
  - number: 82
    latin: >-
      Assidentem conspirati specie officii circumsteterunt, ilicoque Cimber Tillius, qui primas partes susceperat, quasi aliquid rogaturus propius accessit renventique et gestu in aliud tempus differenti ab utroque umero togam adprehendit: deinde clamantem: 'ista quidem vis est!' alter e Cascis aversum vulnerat paulum infra iugulum. Caesar Cascae brachium arreptum graphio traiecit conatusque prosilire alio vulnere tardatus est; utque animadvertit undique se strictis pugionibus peti, toga caput obvoluit, simul sinistra manu sinum ad ima crura deduxit, quo honestius caderet etiam inferiore corporis parte velata. Atque ita tribus et viginti plagis confossus est uno modo ad primum ictum gemitu sine voce edito, etsi tradiderunt quidam Marco Bruto irruenti dixisse: καὶ σὺ τέκνον; Exanimis diffugientibus cunctis aliquamdiu iacuit, donec lecticae impositum, dependente brachio, tres servoli domum rettulerunt. Nec in tot vulneribus, ut Antistius medicus existimabat, letale ullum repertum est, nisi quod secundo loco in pectore acceperat. Fuerat animus coniuratis corpus occisi in Tiberim trahere, bona publicare, acta rescindere, sed metu Marci Antoni consulis et magistri equitum Lepidi destiterunt.
    german: >-
      Als Cäsar sich setzte, umringten die Verschwörer ihn unter dem Anschein einer Ehrbezeugung. Sofort trat Tullius Cimber, der die erste Rolle übernommen hatte, näher an ihn heran, als wenn er ihn um etwas bitten wollte. Als Cäsar ihn durch eine Handbewegung auf eine andere Zeit verwies, fasste er ihn auf beiden Schultern an der Toga, und als Cäsar ausrief: "Das ist ja Gewalt!", verletzte ihn einer der beiden Cascer von hinten etwas unterhalb der Kehle. Cäsar ergriff den Arm des Cassius und durchbohrte ihn mit dem Schreibgriffel, wurde aber, als er aufspringen wollte,  durch eine zweite Verwundung gehemmt. Und als er bemerkte, dass er von allen Seiten mit gezogenen Dolchen angegriffen wurde, verhüllte er sein Haupt mit seiner Toga, die er zugleich mit der linken Hand bis zu den Füßen herabzog, damit er umso ehrenhafter fiel, nachdem auch der untere Teil des Körpers verhüllt worden war. Und so ist er von 23 Messerstichen durchbohrt worden, wobei er nur beim ersten einen Seufzer ohne Stimme ausgestoßen hatte, obwohl einige Leute überliefert hatten, er hätte zum herbeistürzenden  Brutus gesagt: "Auch du, mein Kind?" Während alle entflohen, lag er eine Zeit lang leblos da, bis drei Sklaven den auf eine Sänfte gelegten Leichnam mit heraushängenden Armen in sein Haus zurücktrugen. Und doch war unter so vielen Wunden, nach dem Bericht seines Leibarztes Antistius, nur eine tödlich, die zweite, die er in der Brust erhalten hatte. Die Verschwörer hatten beabsichtigt, den Leichnam des Ermordeten in den Tiber zu schleifen, sein Vermögen einzuziehen und seine Anordnungen zu kassieren; aber aus Furcht vor dem Konsul Marcus Antonius und vor dem Magister Equitum Lepidus ließen sie davon ab.
source_latin: http://www.thelatinlibrary.com/suetonius/suet.caesar.html
counter: https://www.webfreecounter.com/hit.php?id=zvvonfd&nd=9&style=44
---